// Generated by scripts/generate-verified-payments.ts from payment_links.xlsx.
// Do not edit by hand — run `bun run payments:generate`.
//
// Server-only: import this through `@/lib/payment-verification`, never from a
// client component.

export const VERIFIED_PAYMENT_IDS: readonly string[] = [
  "pay_TiEavLuQAOHrmo",
  "pay_TiwiaPf0jD8ZnB",
  "pay_Tjjljc6XlyeLMp",
  "pay_Tjk36001pCFzSa",
  "pay_Tjk933J3KGOkXA",
  "pay_TjkArYY3ZrEPvr",
  "pay_TjkCuZH07MltyP",
  "pay_TjkDyz4nz8yihB",
  "pay_TjkFAwMGZQI0R8",
  "pay_TjkH8rt7jQZ4Ea",
  "pay_TjkgL0v8f0hE7R",
  "pay_Tjl5Qo4M3ZNqvD",
  "pay_Tjl7W05j5wcMPa",
  "pay_Tjl7x84LnLYt0D",
  "pay_TjlHJSPkgkasYa",
  "pay_TjlYw6FR7asCdy",
  "pay_TjlgN190Ax6LJ5",
  "pay_Tjlha8wkbHJSuH",
  "pay_Tjm6JifIJNrDRW",
  "pay_TjmBH4UqyACvl2",
  "pay_TjmCDf086lgHQ8",
  "pay_TjmL9eJVEM1IFt",
  "pay_TjmLV0mktH1IG6",
  "pay_TjmLj6EWqblJ4U",
  "pay_TjmdXE8t4GR2ip",
  "pay_Tjmi1A4r8RLrU5",
  "pay_TjmlitUMYA9bg9",
  "pay_TjnaQsimRKdFgb",
  "pay_TjnqkO1fewxfda",
  "pay_TjoTmCe2CSj04t",
  "pay_TjpyMZllz48aGU",
  "pay_Tjq4H3CNt8u2GS",
  "pay_Tjqy5YNwQEGSdr",
  "pay_TjrBlPG2b1o8EI",
  "pay_TjrC7pDV0RKXaT",
  "pay_TjrLF77G3x6Llt",
];
