import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import ExcelJS from "exceljs";

/**
 * Turns the Razorpay Payment Page export (`payment_links.xlsx`, repo root) into
 * `src/lib/verified-payment-ids.ts` — the list `scanAttendance` checks a team's
 * self-reported payment ID against.
 *
 * Only the IDs are written. The sheet itself carries payer emails and phone
 * numbers and is gitignored; re-run this whenever a fresh export replaces it.
 *
 * A row counts only when the payment was `captured` for the full fee, so a
 * failed attempt or a test payment never reads as verified at the desk.
 */

const SHEET_PATH = fileURLToPath(
  new URL("../payment_links.xlsx", import.meta.url),
);
const OUTPUT_PATH = fileURLToPath(
  new URL("../src/lib/verified-payment-ids.ts", import.meta.url),
);

const FEE_INR = 200;

const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile(SHEET_PATH);

const sheet = workbook.worksheets[0];
if (!sheet) throw new Error("payment_links.xlsx has no worksheet");

// Columns are found by header text, not by letter, so a re-export that adds or
// reorders columns fails loudly instead of reading the wrong one.
const headers = new Map<string, number>();
sheet.getRow(1).eachCell((cell, column) => {
  headers.set(cell.text.trim().toLowerCase(), column);
});

function column(header: string) {
  const index = headers.get(header);
  if (!index) throw new Error(`payment_links.xlsx has no "${header}" column`);
  return index;
}

const idColumn = column("payment id");
const statusColumn = column("payment status");
const amountColumn = column("total payment amount");

const verified = new Set<string>();
let notCaptured = 0;
let wrongAmount = 0;

sheet.eachRow((row, rowNumber) => {
  if (rowNumber === 1) return;

  const id = row.getCell(idColumn).text.trim();
  if (!id) return;

  if (row.getCell(statusColumn).text.trim().toLowerCase() !== "captured") {
    notCaptured += 1;
    return;
  }
  if (Number(row.getCell(amountColumn).text) !== FEE_INR) {
    wrongAmount += 1;
    return;
  }

  verified.add(id);
});

const ids = [...verified].sort();

writeFileSync(
  OUTPUT_PATH,
  `// Generated by scripts/generate-verified-payments.ts from payment_links.xlsx.
// Do not edit by hand — run \`bun run payments:generate\`.
//
// Server-only: import this through \`@/lib/payment-verification\`, never from a
// client component.

export const VERIFIED_PAYMENT_IDS: readonly string[] = [
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
];
`,
);

console.log(
  `Wrote ${ids.length} verified payment IDs (skipped ${notCaptured} not captured, ${wrongAmount} not ₹${FEE_INR})`,
);
